import logging
import os

logger = logging.getLogger(__name__)

def build_report(
    summary: str, 
    group_name: str
) -> str:
    """Combines summary text into standard digest report formatting.

    Args:
        summary: Markdown summary text returned by LLM.
        group_name: Title of the Telegram group chat.

    Returns:
        Formatted digest report text string.
    """
    digest_output = "TELEGRAM DIGEST OUTPUT\n" + "="*40 + "\n\n"
    
    if summary:
        digest_output += summary + "\n" + "-"*40 + "\n"
    else:
        no_msg = "### Summary\n\n*No messages found.*\n"
        digest_output += no_msg + "-"*40 + "\n"
        
    return digest_output


def finalize_report(
    digest_output: str, 
    all_messages: list[dict], 
    hours_back: int, 
    api_duration: float, 
    output_file: str
) -> None:
    """Appends execution metadata to report output and writes result to disk.

    Args:
        digest_output: Formatted digest text generated by build_report.
        all_messages: Raw list of processed message objects.
        hours_back: Configured lookback window duration in hours.
        api_duration: Time spent executing LLM API call in seconds.
        output_file: Absolute path where the report file will be created.
    """
    if all_messages:
        dates = [m['date'] for m in all_messages]
        time_range = f"{min(dates)} to {max(dates)}"
    else:
        time_range = "N/A"

    metadata = (
        f"\n[METADATA]\n"
        f"- Time Range: {time_range}\n"
        f"- Config Window: last {hours_back} hours\n"
        f"- Total messages processed: {len(all_messages)}\n"
        f"- API Processing Time: {api_duration:.2f}s\n"
    )
    
    final_content = digest_output + metadata
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(final_content)
    
    logger.info(f"Report saved to {output_file}")
